### ISSUE TITLE
Command cannot be an array

### ISSUE THREAD

**Issue by AJIOB** [augustocdias/vscode-shell-command#83]
# Current problem
Error message from VSCode:
```
Could not find input with command '${config:cmake.cmakePath} -E cat test-environment.txt' and taskId 'load-path-value-task'.
```

Bad command from `launch.json`:
```json
        {
            "id": "load-path-value",
            "type": "command",
            "command": "shellCommand.execute",
            "args": {
                "useSingleResult": true,
                "description": "Load PATH value",
                "command": [
                    "${config:cmake.cmakePath}",
                    "-E",
                    "cat",
                    "test-environment.txt"
                ],
                "taskId": "load-path-value-task",
                "cwd": "${command:cmake.buildDirectory}",
                "defaultOptions": [
                    "<Please, reconfigure CMake>",
                ],
            }
        }
```

Good command from `launch.json`:
```json
        {
            "id": "load-path-value",
            "type": "command",
            "command": "shellCommand.execute",
            "args": {
                "useSingleResult": true,
                "description": "Load PATH/LD_LIBRARY_PATH value",
                "command": "${config:cmake.cmakePath} -E cat test-environment.txt",
                "taskId": "load-path-value",
                "cwd": "${command:cmake.buildDirectory}",
                "defaultOptions": [
                    "<Please, reconfigure CMake>",
                ],
            }
        }
```

The difference is in `command`. As I can see, `command` may be an array of strings too. Why the variables are not resolved in this way?

Environment:
* plugin version 1.9.1
* VSCode version 1.87.0
* OS: Windows x64 and Ubuntu 22.04 x86_64 (reproducable on both)

# Original problem
The main problem for migrating to the array is a spacing support. If the user have a spaces, as Windows likes, we have an error with the "good" variant:
![image](https://github.com/augustocdias/vscode-shell-command/assets/19916290/77fdf16e-6ed7-4f36-b53b-15b1d24544a8)

That's why I need to manually define every argument for the command line building.

**Comment by MarcelRobitaille** [comment]
Sorry. This was broken in #74. Should be fixed in v1.9.2.

**Comment by AJIOB** [comment]
Hi @MarcelRobitaille 

Thanks for your fix. The variables applying is works for now.

After the upgrading to the 1.9.2 I still have the original problem & create an issue #85 for it.
